<?php
    /** @var  \Danielozano\RouterExample\ViewModel\CatGifViewModel $viewModel */
    $viewModel = $this->getViewModel();
?>

<?php if ($viewModel->getRandomGifEmbedUrl()): ?>
    <div style='width:100%;height:0;padding-bottom:100%;position:relative;'>
        <iframe src="<?= $viewModel->getRandomGifEmbedUrl() ?>" width='100%' height='100%' style='position:absolute' frameBorder='0' class='giphy-embed' allowFullScreen>
        </iframe>
    </div>
<?php endif; ?>
